config/routes.rb
 Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  resources :orders
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :photos, only: [:new, :create, :index, :edit, :update]

  root 'photos#index'
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :user, optional: true
  has_many :line_items
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      flash[:success] = 'Photo added!'
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      flash[:success] = "Photo edited!"
      redirect_to photos_path
    else
      render 'edit'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image, :remove_image)
  end
end

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <%= render "shared/errors", object: @photo %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <% if @photo.image_data %>
    <%= image_tag @photo.image_url(:thumb) %>
    Remove Attachment: <%= f.check_box :remove_image %>
  <% end %>
  <%= f.hidden_field :image, value: @photo.cached_image_data %>
  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/photos/_photo.html.erb
<div>
  <% if photo.image_data? %>
    <%= image_tag photo.image_url(:thumb) %>
  <% end %>
  <p><%= photo.title %> | <%= link_to 'Edit', edit_photo_path(photo) %> | <%= button_to 'Add to cart', line_items_path(photo_id: photo), class: 'button is-warning add-to-cart' %></p>
</div>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<%= link_to 'Add Photo', new_photo_path %>

<%= render @photos %>

app/views/photos/new.html.erb
<h1>Add Photo</h1>

<%= render 'form' %>